# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='echo.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\necho.proto\"\x14\n\x03Set\x12\r\n\x05value\x18\x01 \x01(\t2 \n\x04\x45\x63ho\x12\x18\n\x08Response\x12\x04.Set\x1a\x04.Set\"\x00\x62\x06proto3')
)




_SET = _descriptor.Descriptor(
  name='Set',
  full_name='Set',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Set.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=34,
)

DESCRIPTOR.message_types_by_name['Set'] = _SET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Set = _reflection.GeneratedProtocolMessageType('Set', (_message.Message,), {
  'DESCRIPTOR' : _SET,
  '__module__' : 'echo_pb2'
  # @@protoc_insertion_point(class_scope:Set)
  })
_sym_db.RegisterMessage(Set)



_ECHO = _descriptor.ServiceDescriptor(
  name='Echo',
  full_name='Echo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=36,
  serialized_end=68,
  methods=[
  _descriptor.MethodDescriptor(
    name='Response',
    full_name='Echo.Response',
    index=0,
    containing_service=None,
    input_type=_SET,
    output_type=_SET,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ECHO)

DESCRIPTOR.services_by_name['Echo'] = _ECHO

# @@protoc_insertion_point(module_scope)
